name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=1.0.${{ github.run_number }} -DgenerateBackupPoms=false
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests=true
        working-directory: lib/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
